name: Android CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1-31 * *"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    # Download & install the Android SDK.
    - uses: malinskiy/action-android/install-sdk@release/0.1.2

    # Set up platform tools like adb.
    - run: sdkmanager platform-tools

    # Start ADB (and verify that pathing is working correctly).
    - run: adb devices

    # Verify $ANDROID_HOME is properly set for later Gradle commands.
    - run: echo $ANDROID_HOME
    
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew 
    
    - uses: actions/checkout@v1
    - uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
      with:
        cmd: ./gradlew connectedAndroidTest
        api: 28
        tag: default
        abi: x86_64
    
    
    
   # - uses: actions/checkout@v3
   # - name: set up JDK 11
   #   uses: actions/setup-java@v3
   #   with:
   #     java-version: '11'
   #     distribution: 'temurin'
   #     cache: gradle

   # - name: Grant execute permission for gradlew
   #   run: chmod +x gradlew
   # - name: Build with Gradle
   #   uses: ReactiveCircus/android-emulator-runner@v2.24.0
   #   with:
   #     api-level: 28
   #     script: ./gradlew connectedAndroidTest
